-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '4ca5fe609810fa92' HASH 'c338c293ed6d0b9f1b4a6aea7c23e48b149e9d0fa23bd77663f84097e2115d2c' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 17) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "ROLE_ID" BIGINT,
    "EMAIL" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");        
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, '$2a$10$.gfRiJbGXeXA2j1tLzKaNOJ66UmhMyclsGZqND75tYsTKi3F4ngG.', 'admin', 1, NULL),
(2, '$2a$10$VqEbcPMvDEu/wfeCBES4GO/1bGIh7lE/ADvPdsGUxyprrKztPonTm', 'user', 2, NULL),
(3, '$2a$10$1fovUGlsRcfK7qIMBAgqKOXV81HEttQRRPSTTjVhKbpdIXbT2loJ2', 'mustank', 1, NULL),
(4, '$2a$10$Ao1Xl0IRDkGNXnLaj1FE4ePKsufmzNxalpkUszI5HWBV06sdodOLy', 'normaluser', 2, NULL),
(5, '$2a$10$hDWG7lFPsDkjp77zYxMtOeeVDBZKeW7g8bAUPAG/n4evvbQoBBMmi', 'jsemtunovy', 2, 'jsem@nejsem.cz'),
(6, '$2a$10$QzDq0u1luZaGBG5lDBuNzuACuoSVUjM2Yqwz/Z1jqTOznUzb/uVDW', 'dalsinovy', 2, 'dalsi@novy.cz'),
(7, '$2a$10$T0.EzfqTHQtOexfl13s9/e6DhE5L7YKdUDsYPiqgMtXCwE1PuIXNG', 'uplnenovy', 2, 'uplne@novy.cz'),
(8, '$2a$10$Pw9R2.9iiLn0WOO2B7bxNuVMXHqlrbr65nolSqMuU7QGsu391n2Nu', 'tendalsi', 2, 'ten@dalsi.cz'),
(9, '$2a$10$52a7Ncu2KXtmBwguxt.j3.RH4bjghyqWGKav3ttxzwUFWseJgQUI6', 'Jossi', 2, 'jossi@cokoli.cz'),
(16, '$2a$10$LmP3QjG0U0S5oLEbCeSkoOzC7xWlsrPB0tatxH.DaaP3.ryg5JEbS', 'hlavaty', 13, 'hlavni@urad.cz');       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FKP56C1712K691LHSYEWCSSF40F" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLES"("ID") NOCHECK;           
