SCRIPT TO 'backup.sql';
SCRIPT
CREATE USER IF NOT EXISTS "SA" SALT '8fbcfec7eb63801e' HASH '9a46dbefaa433a2137648060270d6b2f346cf71ebac339e6575629f728d0bc79' ADMIN;
CREATE SEQUENCE "PUBLIC"."MEMBERSHIP_SEQ" START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."ORGANIZATION_SEQ" START WITH 1 RESTART WITH 851 INCREMENT BY 50;
CREATE CACHED TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORGANIZATION"(
                                                             "RN_" INTEGER NOT NULL,
                                                             "ID" BIGINT,
                                                             "ORG_TYPE" CHARACTER VARYING(31) NOT NULL,
                                                             "ADDRESS" CHARACTER VARYING(255),
                                                             "CASE_NUMBER" CHARACTER VARYING(255),
                                                             "CONTACT_EMAIL" CHARACTER VARYING(255),
                                                             "CONTACT_PERSON" CHARACTER VARYING(255),
                                                             "FOUNDING_DATE" CHARACTER VARYING(255),
                                                             "FOUNDING_DATE_RAW" CHARACTER VARYING(255),
                                                             "NAME" CHARACTER VARYING(255),
                                                             "REGISTRATION_NUMBER" CHARACTER VARYING(255),
                                                             "TYPE" ENUM('COMMUNITY', 'PARTNER')
);
ALTER TABLE "PUBLIC"."HTE_ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORGANIZATION;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORGANIZATION1"(
                                                              "RN_" INTEGER NOT NULL,
                                                              "ID" BIGINT,
                                                              "ORG_TYPE" CHARACTER VARYING(31) NOT NULL,
                                                              "CONTACT_EMAIL" CHARACTER VARYING(255),
                                                              "CONTACT_PERSON" CHARACTER VARYING(255),
                                                              "NAME" CHARACTER VARYING(255),
                                                              "TYPE" ENUM('COMMUNITY', 'PARTNER')
);
ALTER TABLE "PUBLIC"."HTE_ORGANIZATION1" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F9" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORGANIZATION1;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORGANIZATION0"(
                                                              "RN_" INTEGER NOT NULL,
                                                              "ID" BIGINT,
                                                              "ORG_TYPE" CHARACTER VARYING(31) NOT NULL,
                                                              "ADDRESS" CHARACTER VARYING(255),
                                                              "CASE_NUMBER" CHARACTER VARYING(255),
                                                              "FOUNDING_DATE" CHARACTER VARYING(255),
                                                              "FOUNDING_DATE_RAW" CHARACTER VARYING(255),
                                                              "NAME" CHARACTER VARYING(255),
                                                              "REGISTRATION_NUMBER" CHARACTER VARYING(255),
                                                              "TYPE" ENUM('COMMUNITY', 'PARTNER')
);
ALTER TABLE "PUBLIC"."HTE_ORGANIZATION0" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F92" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORGANIZATION0;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_MEMBERSHIP"(
                                                           "RN_" INTEGER NOT NULL,
                                                           "ID" BIGINT,
                                                           "MEMBER_ID" BIGINT,
                                                           "ORGANIZATION_ID" BIGINT,
                                                           "ROLE" ENUM('COMMUNITY_ADMIN', 'COMMUNITY_MEMBER', 'PARTNER_ADMIN', 'PARTNER_MEMBER')
);
ALTER TABLE "PUBLIC"."HTE_MEMBERSHIP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_MEMBERSHIP;
CREATE CACHED TABLE "PUBLIC"."ACTIVITY"(
    "DATE" DATE,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "TITLE" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."ACTIVITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACTIVITY;
CREATE CACHED TABLE "PUBLIC"."ACTIVITY_COMMUNITY"(
    "ACTIVITY_ID" BIGINT NOT NULL,
    "COMMUNITY_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACTIVITY_COMMUNITY;
CREATE CACHED TABLE "PUBLIC"."CARS"(
    "DONE" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "TITLE" CHARACTER VARYING(50) NOT NULL,
    "LICENCE_PLATE" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."CARS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CARS;
CREATE CACHED TABLE "PUBLIC"."DRIVERS"(
    "DRUNK" BOOLEAN NOT NULL,
    "CAR_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."DRIVERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DRIVERS;
CREATE CACHED TABLE "PUBLIC"."ITEMS"(
    "DONE" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."ITEMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_42" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEMS;
CREATE CACHED TABLE "PUBLIC"."COMMUNITY"(
    "ID" BIGINT NOT NULL,
    "ADDRESS" CHARACTER VARYING(255),
    "CASE_NUMBER" CHARACTER VARYING(255),
    "FOUNDING_DATE" CHARACTER VARYING(255),
    "REGISTRATION_NUMBER" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."COMMUNITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 169 +/- SELECT COUNT(*) FROM PUBLIC.COMMUNITY;
CREATE CACHED TABLE "PUBLIC"."MEMBERSHIP"(
    "ID" BIGINT NOT NULL,
    "MEMBER_ID" BIGINT NOT NULL,
    "ORGANIZATION_ID" BIGINT NOT NULL,
    "ROLE" ENUM('COMMUNITY_ADMIN', 'COMMUNITY_MEMBER', 'PARTNER_ADMIN', 'PARTNER_MEMBER')
);
ALTER TABLE "PUBLIC"."MEMBERSHIP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_CD" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEMBERSHIP;
CREATE CACHED TABLE "PUBLIC"."ORGANIZATION"(
    "ID" BIGINT NOT NULL,
    "ORG_TYPE" CHARACTER VARYING(31) NOT NULL,
    "ADDRESS" CHARACTER VARYING(255),
    "CASE_NUMBER" CHARACTER VARYING(255),
    "CONTACT_EMAIL" CHARACTER VARYING(255),
    "CONTACT_PERSON" CHARACTER VARYING(255),
    "FOUNDING_DATE" CHARACTER VARYING(255),
    "FOUNDING_DATE_RAW" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "REGISTRATION_NUMBER" CHARACTER VARYING(255),
    "TYPE" ENUM('COMMUNITY', 'PARTNER')
);
ALTER TABLE "PUBLIC"."ORGANIZATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");
-- 676 +/- SELECT COUNT(*) FROM PUBLIC.ORGANIZATION;
CREATE CACHED TABLE "PUBLIC"."PARTICIPATION_REQUEST"(
    "AMOUNT_APPROVED" FLOAT(53),
    "AMOUNT_REQUESTED" FLOAT(53),
    "COMMUNITY_ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "CREATOR_USER_ID" BIGINT NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "MANAGER_ID" BIGINT,
    "PARTNER_ID" BIGINT NOT NULL,
    "PROGRAM_ID" BIGINT NOT NULL,
    "UPDATED_AT" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PROPOSAL_TEXT" CHARACTER VARYING,
    "STATUS" ENUM('ACCEPTED', 'CANCELLED', 'DENIED', 'PARTIAL', 'PENDING')
);
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPATION_REQUEST;
CREATE CACHED TABLE "PUBLIC"."PARTICIPATION_REQUEST_ATTACHMENT"(
    "FILE_SIZE" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "REQUEST_ID" BIGINT NOT NULL,
    "FILE_TYPE" CHARACTER VARYING(255),
    "FILENAME" CHARACTER VARYING(255),
    "STORAGE_PATH" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST_ATTACHMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2C" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPATION_REQUEST_ATTACHMENT;
CREATE CACHED TABLE "PUBLIC"."PROGRAM"(
    "AMOUNT_MAX" INTEGER,
    "CREATOR_COMMUNITY_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "MANAGER_ID" BIGINT,
    "PARTNER_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PROGRAM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROGRAM;
CREATE CACHED TABLE "PUBLIC"."PROGRAM_MEMBERS"(
    "MEMBER_ID" BIGINT NOT NULL,
    "PROGRAM_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROGRAM_MEMBERS;
CREATE CACHED TABLE "PUBLIC"."PROGRAM_SHARED_COMMUNITIES"(
    "COMMUNITY_ID" BIGINT NOT NULL,
    "PROGRAM_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROGRAM_SHARED_COMMUNITIES;
CREATE CACHED TABLE "PUBLIC"."PARTNER"(
    "ID" BIGINT NOT NULL,
    "USER_ID" BIGINT,
    "CONTACT_EMAIL" CHARACTER VARYING(255),
    "CONTACT_PERSON" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PARTNER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PARTNER;
CREATE CACHED TABLE "PUBLIC"."ROLES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."ROLES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4A8" PRIMARY KEY("ID");
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.ROLES;
CREATE CACHED TABLE "PUBLIC"."TASKS"(
    "COMPLETED" BOOLEAN NOT NULL,
    "ESTIMATED_DAYS" INTEGER NOT NULL,
    "ESTIMATED_HOURS" INTEGER NOT NULL,
    "ASSIGNED_MEMBER_ID" BIGINT,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "PARENT_ID" BIGINT,
    "PROGRAM_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."TASKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TASKS;
CREATE CACHED TABLE "PUBLIC"."TOWNS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "POSTAL_CODE" CHARACTER VARYING(10) NOT NULL,
    "TOWN" CHARACTER VARYING(100) NOT NULL
);
ALTER TABLE "PUBLIC"."TOWNS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOWNS;
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "ROLE_ID" BIGINT,
    "EMAIL" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;
CREATE CACHED TABLE "PUBLIC"."MEMBER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "USER_ID" BIGINT,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PARTNER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEMBER;
ALTER TABLE "PUBLIC"."ROLES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4A" UNIQUE NULLS DISTINCT ("NAME");
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" UNIQUE NULLS DISTINCT ("USER_ID");
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("USERNAME");
ALTER TABLE "PUBLIC"."PARTNER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" UNIQUE NULLS DISTINCT ("USER_ID");
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST_ATTACHMENT" ADD CONSTRAINT "PUBLIC"."FKOPYGCV543KWLDE4KOGCR1G86B" FOREIGN KEY("REQUEST_ID") REFERENCES "PUBLIC"."PARTICIPATION_REQUEST"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEMBERSHIP" ADD CONSTRAINT "PUBLIC"."FKHELGQR6JJ4C3BJC40JMBCTMT9" FOREIGN KEY("ORGANIZATION_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ACTIVITY_COMMUNITY" ADD CONSTRAINT "PUBLIC"."FKTN02COWJ6ICF2GB8MY522QHUW" FOREIGN KEY("COMMUNITY_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEMBERSHIP" ADD CONSTRAINT "PUBLIC"."FKEJ551MO6X4EPEI474YS7OJB7C" FOREIGN KEY("MEMBER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM" ADD CONSTRAINT "PUBLIC"."FKHUT1TUNNIIXUQ2T5WCBFLMC9W" FOREIGN KEY("PARTNER_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FKOYSPPVV4QY660A7CP13D0TY6N" FOREIGN KEY("MANAGER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM_MEMBERS" ADD CONSTRAINT "PUBLIC"."FK9TKD6I99Q1KQS92D3SFM0DHLG" FOREIGN KEY("PROGRAM_ID") REFERENCES "PUBLIC"."PROGRAM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM_SHARED_COMMUNITIES" ADD CONSTRAINT "PUBLIC"."FK6PR8DHJAXT6BD35BRQXYGJXVX" FOREIGN KEY("COMMUNITY_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FKEG31P6379MLP1N2LCB17FL5MV" FOREIGN KEY("CREATOR_USER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."FKEU9624SUPJA6YUA83036IPA9T" FOREIGN KEY("PARTNER_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TASKS" ADD CONSTRAINT "PUBLIC"."FKG6DWQACR7GRXAMXJHTB6D2MYR" FOREIGN KEY("PROGRAM_ID") REFERENCES "PUBLIC"."PROGRAM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ACTIVITY_COMMUNITY" ADD CONSTRAINT "PUBLIC"."FK24TF5QFGLYOT9Y3DSKMMFKX5T" FOREIGN KEY("ACTIVITY_ID") REFERENCES "PUBLIC"."ACTIVITY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM_SHARED_COMMUNITIES" ADD CONSTRAINT "PUBLIC"."FK2M8VVD8A3MAAVNL4LOAQAU1AW" FOREIGN KEY("PROGRAM_ID") REFERENCES "PUBLIC"."PROGRAM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TASKS" ADD CONSTRAINT "PUBLIC"."FKMHDA52TOAC2WESO6474WMLDTN" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."TASKS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."FKE6YO8TN29SO0KDD1MW4QK8TGH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM" ADD CONSTRAINT "PUBLIC"."FKK4APTF9QRYLBX57V5RVEQ4X38" FOREIGN KEY("CREATOR_COMMUNITY_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FK2021RF8W5A3PUSC2KQRDBD787" FOREIGN KEY("COMMUNITY_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DRIVERS" ADD CONSTRAINT "PUBLIC"."FKK3XT9Q1JOT6100FO7MP0WM2PW" FOREIGN KEY("CAR_ID") REFERENCES "PUBLIC"."CARS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FKP56C1712K691LHSYEWCSSF40F" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM_MEMBERS" ADD CONSTRAINT "PUBLIC"."FK1WKI26XR9YEPT63G7T903CDB9" FOREIGN KEY("MEMBER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FK22UCPWBTLM2G6I4EDWYCRPDQ5" FOREIGN KEY("PARTNER_ID") REFERENCES "PUBLIC"."ORGANIZATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FKT1KDO8GS4RG72UPDBX9MOPKAT" FOREIGN KEY("PROGRAM_ID") REFERENCES "PUBLIC"."PROGRAM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TASKS" ADD CONSTRAINT "PUBLIC"."FKAPX7ISK7ACU5L3FHQ861PKPXI" FOREIGN KEY("ASSIGNED_MEMBER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROGRAM" ADD CONSTRAINT "PUBLIC"."FK96DW9GMS7HGBWL8L2PLIH96H9" FOREIGN KEY("MANAGER_ID") REFERENCES "PUBLIC"."MEMBER"("ID") NOCHECK;
(101 rows, 50 ms)
