-- SQL Script for creating database and inserting data from the Excel file
-- Database Name: CzechCommunitiesDB
-- Table Name: Communities
-- Columns: Name, RegistrationNumber, CaseNumber, FoundingDate, Address

-- Create the database
CREATE DATABASE CzechCommunitiesDB;

-- Use the database
USE CzechCommunitiesDB;

-- Create the table
CREATE TABLE Communities (
                          Name VARCHAR(255),
                          RegistrationNumber VARCHAR(50),
                          CaseNumber VARCHAR(255),
                          FoundingDate VARCHAR(50),
                          Address VARCHAR(255)
);

-- Insert data extracted from the Excel rows
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('SPOLEK společnost s ručením omezeným', '45791252', 'C 13779 vedená u Městského soudu v Praze', '21. října 1992', 'Petra Bezruče 921/33, Kobylisy, 182 00 Praha 8');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('„SPOLEK”', '1374826', 'L 13591 vedená u Krajského soudu v Ostravě', '1. ledna 2014', 'č.p. 126, 793 97 Slezské Rudoltice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Berla, Chotěboř', '462055', 'L 9126 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Za Vlasárnou 370, 583 01 Chotěboř');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro kulturu a rozvoj Nehasic', '2989646', 'L 9152 vedená u Krajského soudu v Ústí nad Labem', '21. května 2014', 'Nehasice 54, 438 01 Bitozeves');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů ZŠ Krucemburk', '26634660', 'L 9461 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Školní 440, 582 66 Krucemburk');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Cesta lesem', '3058590', 'L 59540 vedená u Městského soudu v Praze', '21. června 2014', 'č.p. 170, 267 54 Praskolesy');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel železnice v Chotěboři', '26606526', 'L 9445 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', '5. května 491, 583 01 Chotěboř');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Základní a Mateřské škole v Žarošicích AKTOVKA', '3083659', 'L 19902 vedená u Krajského soudu v Brně', '28. června 2014', 'č.p. 321, 696 34 Žarošice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Přátelé školy ve Ždírci nad Doubravou', '26631105', 'L 9456 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Chrudimská 77, 582 63 Ždírec nad Doubravou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('SPOLEK NA OCHRANU PŘÍRODY, PAMÁTEK A ŽIVOTNÍHO PROSTŘEDÍ VESNICE SPYTICE A OKOLÍ', '27002471', 'L 9498 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Spytice 10, 582 82 Vilémov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro chemickou a hutní výrobu, akciová společnost', '11789', 'B 47 vedená u Krajského soudu v Ústí nad Labem', '31. prosince 1990', 'Ústí nad Labem, Revoluční 1930/86, PSČ 40032');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Radia R', '3315291', 'L 19998 vedená u Krajského soudu v Brně', '11. září 2014', 'Šumavská 492/8, Ponava, 602 00 Brno');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Lísky, z.s.', '2851946', 'L 6384 vedená u Krajského soudu v Českých Budějovicích', '23. dubna 2014', 'Lísky 20, 396 01 Koberovice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek mlžněvědných studií', '2918731', 'L 9092 vedená u Krajského soudu v Hradci Králové', '14. května 2014', 'Karpatská 177, Kerhartice, 562 04 Ústí nad Orlicí');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vojenských vysloužilců arcivévody Rainera pro Rakovník a okolí, z.s.', '3099709', 'L 60917 vedená u Městského soudu v Praze', '18. června 2014', 'Spalova 2260, Rakovník II, 269 01 Rakovník');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek VODA STUDÉNKY z. s.', '3200451', 'L 9793 vedená u Krajského soudu v Hradci Králové', '8. srpna 2014', 'č.p. 218, 542 12 Radvanice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek zahrádkářů, ochránců přírody a životního prostředí v Josefodole', '1556011', 'L 9398 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Josefodol 16, 582 91 Světlá nad Sázavou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Seniorklub Chotěboř', '26523761', 'L 9407 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Trčků z Lípy 62, 583 01 Chotěboř');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek uživatelů energetických kabelových rozvodů nízkého napětí', '26531224', 'L 9412 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.ev. 25, 583 01 Chotěboř');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek aktivních Zlatohoráků', '2760959', 'L 12099 vedená u Krajského soudu v Ostravě', '29. března 2014', 'Bezručova 144, 793 76 Zlaté Hory');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Javor', '2963183', 'L 9052 vedená u Krajského soudu v Hradci Králové', '12. června 2014', 'č.p. 381, 517 11 Javornice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('"Spolek rodičů a přátel gymnázia v Havlíčkově Brodě"', '60126841', 'L 9229 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Štáflova 2063, 580 01 Havlíčkův Brod');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Krucemburku', '15060349', 'L 9221 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Nám. Jana Zrzavého 13, 582 66 Krucemburk');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek TJ Jóga Přibyslav', '62698702', 'L 9335 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Tyršova 235, 582 22 Přibyslav');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel studentů a školy při Gymnáziu Chotěboř', '27031934', 'L 9516 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Jiráskova 637, 583 01 Chotěboř');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek zahrádkářů Krucemburk', '27017893', 'L 9507 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Nám. Jana Zrzavého 13, 582 66 Krucemburk');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Žďárský vlk', '27023281', 'L 9513 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 164, 580 01 Veselý Žďár');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Fantazáci', '27020657', 'L 9512 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 54, 582 74 Jeřišno');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Zatlanka z.s.', '69155445', 'L 59355 vedená u Městského soudu v Praze', '1. ledna 2014', 'Ostrovského 1823/32, Smíchov, 150 00 Praha 5');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Okrouhlička', '27051277', 'L 9534 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 39, 582 53 Okrouhlička');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Limetka', '3210651', 'L 61094 vedená u Městského soudu v Praze', '8. srpna 2014', 'Borovská 1697, Újezd nad Lesy, 190 16 Praha 9');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek na podporu zámku Skalka - obec Vlastislav', '3228932', 'L 9219 vedená u Krajského soudu v Ústí nad Labem', '13. srpna 2014', 'č.p. 9, 411 14 Vlastislav');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel bonsají Mělník', '3292576', 'L 61150 vedená u Městského soudu v Praze', '13. srpna 2014', 'Nebeského 1909/34, 276 01 Mělník');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel dětí a školy při MŠ Chyšky', '2869659', 'L 6412 vedená u Krajského soudu v Českých Budějovicích', '1. ledna 2014', 'č.p. 119, 398 53 Chyšky');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('SPOLEK CZ s.r.o.', '28826442', 'C 29932 vedená u Krajského soudu v Hradci Králové', '9. prosince 2011', 'Smilova 381, Zelené Předměstí, 530 02 Pardubice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek myslivců a přátel přírody z Jeseníků, Karlov pod Pradědem', '3373258', 'L 13814 vedená u Krajského soudu v Ostravě', '11. září 2014', 'č.p. 276, 793 36 Malá Morávka');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Za lepší Příšovice', '2756919', 'L 8924 vedená u Krajského soudu v Ústí nad Labem', '28. března 2014', 'č.p. 229, 463 46 Příšovice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek voda 2012', '2765101', 'L 19688 vedená u Krajského soudu v Brně', '19. března 2014', 'J. Lady 1911/5, 678 01 Blansko');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek TAMARA', '3234231', 'L 19991 vedená u Krajského soudu v Brně', '15. srpna 2014', 'Petra Jilemnického 361/29, 679 04 Adamov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Strackých žen', '3301036', 'L 61065 vedená u Městského soudu v Praze', '8. srpna 2014', 'č.p. 50, 289 25 Straky');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek zdravého úsudku FILIP', '3053300', 'L 19878 vedená u Krajského soudu v Brně', '2. června 2014', 'Radnická 1007, 592 31 Nové Město na Moravě');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Hlavňovice', '2976188', 'L 6447 vedená u Krajského soudu v Českých Budějovicích', '28. května 2014', 'Volyňská 192, Strakonice II, 386 01 Strakonice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Tradičního karate ČR', '3259676', 'L 61131 vedená u Městského soudu v Praze', '4. srpna 2014', 'Chlebovická 492, Letňany, 199 00 Praha 9');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Nebušice', '3152448', 'L 61006 vedená u Městského soudu v Praze', '4. července 2014', 'Nebušická 677, Nebušice, 164 00 Praha 6');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('SPOLEK RACEK', '3097340', 'L 6469 vedená u Krajského soudu v Českých Budějovicích', '3. července 2014', 'Dolní náměstí 433, 373 44 Zliv');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel stolního tenisu Trutnov', '3185826', 'L 9808 vedená u Krajského soudu v Hradci Králové', '12. srpna 2014', 'Nádražní 189, Střední Předměstí, 541 01 Trutnov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Základní a mateřské škole Vilémov', '2381362', 'L 9705 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Klášter 23, 582 83 Vilémov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Fokus Vysočina', '2474913', 'L 9707 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', '5. května 356, 580 01 Havlíčkův Brod');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek U Andělky, z.s.', '29400171', 'L 13691 vedená u Krajského soudu v Ostravě', '24. června 2014', 'Vítězná 1798/19, Moravská Ostrava, 702 00 Ostrava');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek milců čaje s.r.o.', '48027545', 'C 14397 vedená u Městského soudu v Praze', '11. listopadu 1992', 'Dělnická 1020/54, Holešovice, 170 00 Praha 7');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rozhodců s.r.o.', '28283350', 'C 58519 vedená u Krajského soudu v Brně', '21. dubna 2008', 'Bohuslava Martinů 844/59, Stránice, 602 00 Brno');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro rozvoj venkova o.p.s.', '28322959', 'O 373 vedená u Krajského soudu v Brně', '26. ledna 2009', 'Dalešice 71, PSČ 67554');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek uživatelů vody Polanka', '3179079', 'L 19943 vedená u Krajského soudu v Brně', '29. července 2014', 'Těsnohlídkovo náměstí 1000, 664 01 Bílovice nad Svitavou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek občanů a přátel Slavníče', '22756248', 'L 9653 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 33, 582 55 Slavníč');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek TrojHáček', '22758020', 'L 9651 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Zahradní 313, 582 23 Havlíčkova Borová');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek PRO', '3205690', 'L 9211 vedená u Krajského soudu v Ústí nad Labem', '8. srpna 2014', 'Rooseveltova 2148, Horní Litvínov, 436 01 Litvínov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek skalické NEBE', '2974452', 'L 6437 vedená u Krajského soudu v Českých Budějovicích', '27. května 2014', 'č.p. 48, 392 01 Skalice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek na Pelhřimáku', '1172182', 'L 9675 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Jihlavská 396, 580 01 Havlíčkův Brod');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Rybáři Dolní Krupá', '26573521', 'L 9579 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 1, 582 71 Dolní Krupá');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek TILIA', '22904239', 'L 9625 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 131, 582 57 Lípa');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Kopanin', '2886308', 'L 19728 vedená u Krajského soudu v Brně', '6. května 2014', 'č.p. 96, 588 44 Rohozná');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel místních drah', '66362709', 'L 6992 vedená u Krajského soudu v Plzni', '26. dubna 2002', 'Koterovská 747/95, Lobzy, 326 00 Plzeň');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Kolem dokola', '3070280', 'L 9180 vedená u Krajského soudu v Ústí nad Labem', '24. června 2014', 'č.p. 730, 407 79 Mikulášovice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel československého opevnění Brno s.r.o.', '25596772', 'C 36755 vedená u Krajského soudu v Brně', '14. dubna 2000', 'Luční 199, 666 03 Hradčany');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek ochotných stomatologů, spol. s r.o.', '26201887', 'C 79277 vedená u Městského soudu v Praze', '2. října 2000', 'Pičín 85, okres Příbram, PSČ 26225');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pěstitelů a zpracovatelů brambor z Vysočiny', '22747222', 'L 9657 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Dobrovského 2366, 58001, 580 01 Havlíčkův Brod');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Pro děti a přírodu', '22877428', 'L 9636 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 40, 582 51 Šlapanov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek mediků českých', '69342512', 'L 58 vedená u Městského soudu v Praze', '1. ledna 2014', 'Kateřinská 1660/32, Nové Město, 120 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Sokol Podmoklany', '22825738', 'L 9601 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'č.p. 41, 582 64 Podmoklany');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek dětského pěveckého sboru Svítání', '65991061', 'L 7754 vedená u Městského soudu v Praze', '1. ledna 2014', 'Štefánikova 217/19, Smíchov, 150 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vzájemně podpůrný, tělovýchovný a poznávací', '64808564', 'L 7644 vedená u Městského soudu v Praze', '1. ledna 2014', 'Chalupnická 40/14, 110 00 Praha 10');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů ZŠ Chvaletická, z.s.', '65996577', 'L 7910 vedená u Městského soudu v Praze', '1. ledna 2014', 'Chvaletická 918/3, Hloubětín, 198 00 Praha 9');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vlastníků bytů domu č.p. 100 - obec Chrustenice - 267 12 Loděnice', '64752453', 'L 7927 vedená u Městského soudu v Praze', '1. ledna 2014', 'Chrustenice č. 100, p. Loděnice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('spolek Středisko Bílý Vlk - v likvidaci', '65993187', 'L 7844 vedená u Městského soudu v Praze', '1. ledna 2014', 'K rybárně 2545/11, Horní Počernice, 193 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vlastníků domu Pod nemocnicí 2345, Rakovník v likvidaci', '63806185', 'L 7848 vedená u Městského soudu v Praze', '1. ledna 2014', 'Pod Nemocnicí 2345, Rakovník II, 269 01 Rakovník');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vlastníků garáží Nad Teplárnou, z.s.', '68380674', 'L 7869 vedená u Městského soudu v Praze', '1. ledna 2014', 'Krupná 2171/12, Komořany, 143 00 Praha 4schránka 30');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Bakajda', '62454005', 'L 14045 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Ryžoviště 313, 512 46 Harrachov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Německá škola v Praze', '67361978', 'L 7879 vedená u Městského soudu v Praze', '1. ledna 2014', 'Schwarzenberská 700/1, Jinonice, 158 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro senohrabskou plovárnu a přívoz', '65994353', 'L 7898 vedená u Městského soudu v Praze', '1. ledna 2014', 'Příčná 61, 251 66 Senohraby');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Stará škola Strašice', '65991869', 'L 7779 vedená u Městského soudu v Praze', '1. ledna 2014', 'Malý Chlumec 77, 267 24 Velký Chlumec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Cibulka', '72550121', 'L 8792 vedená u Městského soudu v Praze', '1. ledna 2014', 'V Cibulkách 421/4, Košíře, 150 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek autorizovaných prodejců FORD', '67779069', 'L 8663 vedená u Městského soudu v Praze', '1. ledna 2014', 'Na Chodovci 2457/1, Záběhlice, 141 00 Praha 4');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vlastníků bytů Králův Dvůr, Pod Hájem 309', '67674917', 'L 8646 vedená u Městského soudu v Praze', '1. ledna 2014', 'Pod Hájem 309, 267 01 Králův Dvůr');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel Obchodní akademie Dušní 7, Praha 1', '67775608', 'L 8610 vedená u Městského soudu v Praze', '1. ledna 2014', 'Praha 1, Dušní 7');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy Obchodní akademie Neveklov', '67674992', 'L 8621 vedená u Městského soudu v Praze', '1. ledna 2014', 'Školní 303, 257 56 Neveklov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vlastníků bytů Králův Dvůr, Pod hájem 307', '67675271', 'L 8584 vedená u Městského soudu v Praze', '1. ledna 2014', 'Pod Hájem 307, 267 01 Králův Dvůr');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek PRO GYMNÁZIUM', '67779107', 'L 8566 vedená u Městského soudu v Praze', '1. ledna 2014', 'Lindnerova 517/3, Libeň, 180 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('spolek Setkání v likvidaci', '68379722', 'L 8572 vedená u Městského soudu v Praze', '1. ledna 2014', 'Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Pastelkov', '1731033', 'L 25816 vedená u Městského soudu v Praze', '1. ledna 2014', 'Nad Koupadly 272/9, Strašín, 251 01 Říčany');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek obchodních zástupců v oblasti přímého prodeje v likvidaci', '1758268', 'L 25839 vedená u Městského soudu v Praze', '1. ledna 2014', 'Zděbradská 72, Jažlovice, 251 01 Říčany');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů při ZŠ a MŠ Barrandov', '1736248', 'L 25822 vedená u Městského soudu v Praze', '1. ledna 2014', 'Chaplinovo náměstí 615/1, Hlubočepy, 152 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro záchranu továrny Mastných v Lomnici nad Popelkou', '1676733', 'L 11559 vedená u Krajského soudu v Hradci Králové', '1. ledna 2014', 'Antala Staška 212, 512 51 Lomnice nad Popelkou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Olivers - rozvoj osobnosti člověka', '1689801', 'L 18911 vedená u Krajského soudu v Ostravě', '1. ledna 2014', 'č.p. 941, 739 95 Bystřice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Plenér Venkov v likvidaci', '1698656', 'L 25775 vedená u Městského soudu v Praze', '1. ledna 2014', 'Kaprova 42/14, Staré Město, 110 00 Praha 1');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek příznivců školy při Integrované střední škole hotelového provozu, obchodu a služeb, Příbram, Gen. R. Tesaříka 114', '1693646', 'L 25762 vedená u Městského soudu v Praze', '1. ledna 2014', 'Plzeňská 75, Příbram I, 261 01 Příbram');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel obce Janova nad Nisou', '60253541', 'L 2084 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'č.p. 248, 468 11 Janov nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro ochranu hradu Hamburk', '44556390', 'L 2066 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vojenské historie Liberec', '46749586', 'L 2157 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Dolní Suchá 33, 463 34 Hrádek nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek obyvatel domu č.p. 204 a 205 Staňkovice, z.s.', '64018296', 'L 2154 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Staňkovice č.p. 204 a 205');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek občanů obytného domu čp. 151, v Ústí nad Labem', '44557442', 'L 2210 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Opletalova 151, Neštěmice, 403 31 Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů, přátel a dětí školy při Střední průmyslové škole a Vyšší odborné škole Chomutov, z.s.', '46789812', 'L 2206 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Školní 1060/50, 430 01 Chomutov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro sport,kulturu,vzdělání a poznávání, z.s', '60254165', 'L 2244 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Sněhová 5228/14, Mšeno nad Nisou, 466 04 Jablonec nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek sdružení rodičů a přátel školy 5. ZŠ Jablonec nad Nisou, Pasířská 72', '2134250', 'L 2273 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Pasířská 750/72, 466 01 Jablonec nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Chatová osada U přehrady Žatec', '64018831', 'L 2291 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Bratří Čapků 2154, 438 01 Žatec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel JERGYM, z. s.', '49111639', 'L 2301 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Jeronýmova 425/27, Liberec VII-Horní Růžodol, 460 07 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vojenské historie Ústí nad Labem', '63152487', 'L 2311 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Rabasova 3197/4, Severní Terasa, 400 11 Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek míčových kouzelníků', '1250086', 'L 25067 vedená u Městského soudu v Praze', '1. ledna 2014', 'Rumunská 1459/36, 250 88 Čelákovice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro Rozvoj ZŠ Vašatova 1438, Kladno', '1250302', 'L 25066 vedená u Městského soudu v Praze', '1. ledna 2014', 'Vašatova 1438, 272 01 Kladno');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Neusitz', '1246194', 'L 25055 vedená u Městského soudu v Praze', '1. ledna 2014', 'č.p. 4, 293 01 Plazy');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Fakultní základní škole s rozšířenou výukou jazyků při PedF UK, Drtinova 1861/1, Praha 5 - Smíchov, z.s.', '1304470', 'L 25172 vedená u Městského soudu v Praze', '1. ledna 2014', 'Drtinova 1861/1, Smíchov, 150 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při MŠ Radlická, o.s.', '1350498', 'L 25276 vedená u Městského soudu v Praze', '1. ledna 2014', 'Nad Laurovou 1983/1, Smíchov, 150 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel ZŠ a MŠ Chocerady', '1346792', 'L 25269 vedená u Městského soudu v Praze', '1. ledna 2014', 'č.p. 267, 257 24 Chocerady');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek 64 U Hradeb', '1344820', 'L 25268 vedená u Městského soudu v Praze', '1. ledna 2014', 'Bříšťanská 1687/21, Horní Počernice, 193 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel ZŠ Pečky', '1346857', 'L 25272 vedená u Městského soudu v Praze', '1. ledna 2014', 'Tř. Jana Švermy 342, 289 11 Pečky');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Zděná 2012', '1279858', 'L 25116 vedená u Městského soudu v Praze', '1. ledna 2014', 'č.p. 33, 267 63 Zaječov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Keep it clean', '1335898', 'L 25236 vedená u Městského soudu v Praze', '1. ledna 2014', 'Ovenecká 752/5, Holešovice, 170 00 Praha 7');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek volnočasových aktivit Roztoky, o.s. v likvidaci', '1263137', 'L 25097 vedená u Městského soudu v Praze', '1. ledna 2014', 'Nádražní 842, 252 63 Roztoky');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Zdravé Letňany z. s.', '1334255', 'L 25223 vedená u Městského soudu v Praze', '1. ledna 2014', 'Choceňská 158, Letňany, 199 00 Praha 9');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodáků a přátel města Loun a okolí', '2473836', 'L 518 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Mírové náměstí 35, 440 01 Louny');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel PSDM Hlásek', '41329082', 'L 418 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Sladovnická 309, Liberec XXX-Vratislavice nad Nisou, 463 11 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pro podporu Podještědského gymnázia', '43225136', 'L 446 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Sokolovská 328/17, Liberec XIII-Nové Pavlovice, 460 01 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů Základní školy, Teplice, U Nových lázní 1102', '70693943', 'L 449 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'U Nových lázní 1102/4, 415 01 Teplice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při ZŠ a MŠ Kpt. O. Jaroše Louny, z. s.', '46762523', 'L 475 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Louny');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy Základní škola Novosedlice, okres Teplice z. s.', '70825611', 'L 463 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Vrchoslavská 88/30, 417 31 Novosedlice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel ZŠ Ústí nad Labem, Karla IV.1024', '44225334', 'L 501 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ústí nad Labem, Karla IV. lO24');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel ZŠ Ústí nad Labem, E. Krásnohorské 3084/8', '70226431', 'L 499 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Elišky Krásnohorské 3084/8, Ústí nad Labem-centrum, 400 11 Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('„Spolek pro vlastivědnou práci v Liberci a okolí”', '380024', 'L 275 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Jablonecká 988, Liberec VI-Rochlice, 460 06 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Němců v severních Čechách', '18381545', 'L 282 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ruprechtická 254/119, Liberec XIV-Ruprechtice, 460 14 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek horských vůdců Jizerské Hory', '18381596', 'L 256 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Bedřichov v Jizerských Horách');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek loutkářů v Lounech', '14866587', 'L 251 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Pod Cukrovarem 832, 440 01 Louny');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel Střední průmyslové školy v České Lípě, z. s.', '48282359', 'L 1488 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Havlíčkova 426/5, 47001, 470 01 Česká Lípa');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel ZUŠ Postoloprty', '49120018', 'L 1458 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Postoloprty');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Svobodné základní školy', '43256414', 'L 1449 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'U Přehrady 3196/4, 466 02 Jablonec nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Hokejový klub Klášterec nad Ohří', '47792981', 'L 1542 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Stadion 356, Miřetice u Klášterce nad Ohří, 431 51 Klášterec nad Ohří');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Státní vědecké knihovny v Liberci', '46746498', 'L 1593 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Němců a přátel regionu Krušné hory a jejich předhůří, z.s.', '47793023', 'L 1589 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Na Bělidle 842/3, 430 01 Chomutov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek CAMELLA - NBP, Nový Bor', '49864017', 'L 1722 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Palackého náměstí 183, 473 01 Nový Bor');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rybářů Březno', '2501937', 'L 70123 vedená u Městského soudu v Praze', '1. ledna 2014', 'Březno');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Českého Švýcarska', '46718109', 'L 1688 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Jetřichovice 24');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek Porta Bohemica Litochovice nad Labem', '46772464', 'L 1728 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Litochovice nad Labem 79, 411 33 Prackovice nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Obchodní akademii a Střední odborné škole zemědělské a ekologické, Žatec, z.s.', '46764551', 'L 546 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ul. Sv. Čecha 1180, 438 01 Žatec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel dětí a školy při ZŠ Špičák, Česká Lípa', '65650298', 'L 551 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', '28. října 2733, 470 01 Česká Lípa');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek SOMACH', '88397807', 'L 568 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Jitřní 238, Liberec XXXIII-Machnín, 460 01 Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy ZŠ a MŠ Zákupy, zapsaný spolek', '2495031', 'L 578 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Školní 347, 471 23 Zákupy');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek ústeckých akvaristů', '44226322', 'L 604 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Větrná 2713/2, Severní Terasa, 400 11 Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů žáků Gymnázia a Střední průmyslové školy Duchcov', '65082648', 'L 616 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Masarykova 909/12, 419 01 Duchcov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel školy v Ročově', '46764411', 'L 623 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ročov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Střední škole obchodu a služeb, Teplice, p. o.', '1721828', 'L 628 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Fráni Šrámka 1350/1, Trnovany, 415 01 Teplice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('SPOLEK RODIČŮ A PŘÁTEL GYMNÁZIA LOUNY', '64018130', 'L 630 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Poděbradova 661, 440 01 Louny');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při ZŠ a MŠ Mírová 81, Mimoň', '62237624', 'L 742 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Mírová 81, Mimoň III, 471 24 Mimoň');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel ZŠ Lada', '46750291', 'L 708 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Šluknovská 2904, 470 01 Česká Lípa');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů při Základní škole v Peruci', '60275529', 'L 689 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Komenského 193, 439 07 Peruc');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy ZŠ Ruská, Litvínov v likvidaci', '1720503', 'L 640 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ruská 2059, Horní Litvínov, 436 01 Litvínov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek SNS Smržovka', '16389913', 'L 1143 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Luční 32, 468 51 Smržovka');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů při ZŠ Česká Lípa, Školní 2520', '69410780', 'L 1216 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Školní 2520, 470 01 Česká Lípa');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel města Jablonec nad Nisou', '64669068', 'L 1217 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Mírové náměstí 3100/19, 466 01 Jablonec nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek rodičů a přátel školy při Mateřské škole, Most, Růžová 1427, z.s.', '42139864', 'L 1153 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Růžová 1427, 434 01 Most');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek studentů sociologie FF UK, z. s.', '2506475', 'L 26626 vedená u Městského soudu v Praze', '1. ledna 2014', 'Celetná 562/20, Staré Město, 110 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek ActiTmel.cz', '2475421', 'L 26565 vedená u Městského soudu v Praze', '1. ledna 2014', 'Vavřineč 107, 277 31 Malý Újezd');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('spolek Dvorek', '2487403', 'L 26584 vedená u Městského soudu v Praze', '1. ledna 2014', 'Šlikova 1220/47, Břevnov (Praha 6), 169 00 Praha');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek na ochranu Lužických hor', '2438143', 'L 137 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Trávník');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek ochrany zvířat Ústí nad Labem', '2422182', 'L 139 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Ústí nad Labem');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek přátel Severáku a Jizerských hor', '2438151', 'L 135 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', '468 11 Janov nad Nisou');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek vojenských vysloužilců MUDr. Václava Šamánka v Liberci', '435180', 'L 219 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Liberec');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek filmových amatérů Litvínov', '2364727', 'L 207 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', '436 01 Litvínov');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek pěstitelů kaktusů Děčín', '2368625', 'L 193 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'č.p. 25, 407 24 Valkeřice');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek spoluvlastníků domu čp. 2056 v Lounech, ulice J. Švermy', '26594234', 'L 4384 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Jana Švermy 2056, 440 01 Louny');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Spolek "Eremy ART"', '26595346', 'L 4382 vedená u Krajského soudu v Ústí nad Labem', '1. ledna 2014', 'Husova 771, 441 01 Podbořany');
INSERT INTO Communities (Name, RegistrationNumber, CaseNumber, FoundingDate, Address) VALUES ('Místní spolek DobroMysl', '21041504', 'L 14592 vedená u Krajského soudu v Hradci Králové', '6. ledna 2024', 'č.p. 205, 543 72 Rudník');
-- Note: The data was truncated in the input, so this script includes all provided records up to the truncation point. If more data is available, additional INSERT statements can be added.