-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '4ca5fe609810fa92' HASH 'c338c293ed6d0b9f1b4a6aea7c23e48b149e9d0fa23bd77663f84097e2115d2c' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."MEMBER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 12) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "ROLE" CHARACTER VARYING(255),
    "USER_ID" BIGINT
);              
ALTER TABLE "PUBLIC"."MEMBER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.MEMBER;   
INSERT INTO "PUBLIC"."MEMBER" VALUES
(3, 'dalsi@novy.cz', 'dalsinovy', 'member', 6),
(5, NULL, 'user', 'member', 2),
(6, 'ten@dalsi.cz', 'tendalsi', NULL, 8),
(7, 'jossi@cokoli.cz', 'Jossi', NULL, 9),
(8, 'anna.manager@org.com', 'Anna Schmidt', 'MANAGER', 2),
(9, 'bob.volunteer@org.com', 'Bob Kowalski', 'VOLUNTEER', 3),
(10, 'clara@org.com', 'Clara Nowak', 'VOLUNTEER', 4),
(11, 'david@testing.com', 'David Test', 'VOLUNTEER', NULL);            
