CREATE TABLE IF NOT EXISTS tasks (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255),
    completed BOOLEAN DEFAULT FALSE,
    description VARCHAR(1000),
    estimated_days INT DEFAULT 0,
    estimated_hours INT DEFAULT 0,
    program_id BIGINT,
    assigned_member_id BIGINT,
    parent_id BIGINT
    );
